TARGET := iphone:clang:6.1:5.0
ARCHS := armv7 armv7s

include $(THEOS)/makefiles/common.mk

TOOL_NAME = gcpassesfix-run
gcpassesfix-run_FILES = gcpassesfix-run.c
gcpassesfix-run_INSTALL_PATH = /usr/libexec

include $(THEOS_MAKE_PATH)/tool.mk
